//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/Netcracker/pgskipper-operator-core/api/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomQueries) DeepCopyInto(out *CustomQueries) {
	*out = *in
	if in.NamespacesList != nil {
		in, out := &in.NamespacesList, &out.NamespacesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomQueries.
func (in *CustomQueries) DeepCopy() *CustomQueries {
	if in == nil {
		return nil
	}
	out := new(CustomQueries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDataBase) DeepCopyInto(out *ExternalDataBase) {
	*out = *in
	if in.RestoreConfig != nil {
		in, out := &in.RestoreConfig, &out.RestoreConfig
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDataBase.
func (in *ExternalDataBase) DeepCopy() *ExternalDataBase {
	if in == nil {
		return nil
	}
	out := new(ExternalDataBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTests) DeepCopyInto(out *IntegrationTests) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.TestList != nil {
		in, out := &in.TestList, &out.TestList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTests.
func (in *IntegrationTests) DeepCopy() *IntegrationTests {
	if in == nil {
		return nil
	}
	out := new(IntegrationTests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patroni) DeepCopyInto(out *Patroni) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patroni.
func (in *Patroni) DeepCopy() *Patroni {
	if in == nil {
		return nil
	}
	out := new(Patroni)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniServices) DeepCopyInto(out *PatroniServices) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(PatroniServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniServices.
func (in *PatroniServices) DeepCopy() *PatroniServices {
	if in == nil {
		return nil
	}
	out := new(PatroniServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PatroniServices) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniServicesList) DeepCopyInto(out *PatroniServicesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PatroniServices, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniServicesList.
func (in *PatroniServicesList) DeepCopy() *PatroniServicesList {
	if in == nil {
		return nil
	}
	out := new(PatroniServicesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PatroniServicesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniServicesSpec) DeepCopyInto(out *PatroniServicesSpec) {
	*out = *in
	if in.Patroni != nil {
		in, out := &in.Patroni, &out.Patroni
		*out = new(Patroni)
		**out = **in
	}
	if in.BackupDaemon != nil {
		in, out := &in.BackupDaemon, &out.BackupDaemon
		*out = new(apiv1.BackupDaemon)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricCollector != nil {
		in, out := &in.MetricCollector, &out.MetricCollector
		*out = new(apiv1.MetricCollector)
		(*in).DeepCopyInto(*out)
	}
	if in.IntegrationTests != nil {
		in, out := &in.IntegrationTests, &out.IntegrationTests
		*out = new(IntegrationTests)
		(*in).DeepCopyInto(*out)
	}
	if in.VaultRegistration != nil {
		in, out := &in.VaultRegistration, &out.VaultRegistration
		*out = new(apiv1.VaultRegistration)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(Policies)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudSql != nil {
		in, out := &in.CloudSql, &out.CloudSql
		*out = new(apiv1.CloudSql)
		**out = **in
	}
	if in.SiteManager != nil {
		in, out := &in.SiteManager, &out.SiteManager
		*out = new(SiteManager)
		(*in).DeepCopyInto(*out)
	}
	in.PowaUI.DeepCopyInto(&out.PowaUI)
	in.ReplicationController.DeepCopyInto(&out.ReplicationController)
	in.Pooler.DeepCopyInto(&out.Pooler)
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(Tracing)
		**out = **in
	}
	if in.ExternalDataBase != nil {
		in, out := &in.ExternalDataBase, &out.ExternalDataBase
		*out = new(ExternalDataBase)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgresExporter != nil {
		in, out := &in.PostgresExporter, &out.PostgresExporter
		*out = new(PostgresExporter)
		(*in).DeepCopyInto(*out)
	}
	in.QueryExporter.DeepCopyInto(&out.QueryExporter)
	if in.Tls != nil {
		in, out := &in.Tls, &out.Tls
		*out = new(Tls)
		**out = **in
	}
	if in.PgBackRest != nil {
		in, out := &in.PgBackRest, &out.PgBackRest
		*out = new(PgBackRest)
		(*in).DeepCopyInto(*out)
	}
	in.PrivateRegistry.DeepCopyInto(&out.PrivateRegistry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniServicesSpec.
func (in *PatroniServicesSpec) DeepCopy() *PatroniServicesSpec {
	if in == nil {
		return nil
	}
	out := new(PatroniServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniServicesStatus) DeepCopyInto(out *PatroniServicesStatus) {
	*out = *in
	out.SiteManagerStatus = in.SiteManagerStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PatroniServicesStatusCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniServicesStatus.
func (in *PatroniServicesStatus) DeepCopy() *PatroniServicesStatus {
	if in == nil {
		return nil
	}
	out := new(PatroniServicesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniServicesStatusCondition) DeepCopyInto(out *PatroniServicesStatusCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniServicesStatusCondition.
func (in *PatroniServicesStatusCondition) DeepCopy() *PatroniServicesStatusCondition {
	if in == nil {
		return nil
	}
	out := new(PatroniServicesStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgBackRest) DeepCopyInto(out *PgBackRest) {
	*out = *in
	out.S3 = in.S3
	if in.Rwx != nil {
		in, out := &in.Rwx, &out.Rwx
		*out = new(apiv1.Storage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgBackRest.
func (in *PgBackRest) DeepCopy() *PgBackRest {
	if in == nil {
		return nil
	}
	out := new(PgBackRest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policies) DeepCopyInto(out *Policies) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policies.
func (in *Policies) DeepCopy() *Policies {
	if in == nil {
		return nil
	}
	out := new(Policies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pooler) DeepCopyInto(out *Pooler) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pooler.
func (in *Pooler) DeepCopy() *Pooler {
	if in == nil {
		return nil
	}
	out := new(Pooler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Postgres) DeepCopyInto(out *Postgres) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Postgres.
func (in *Postgres) DeepCopy() *Postgres {
	if in == nil {
		return nil
	}
	out := new(Postgres)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresExporter) DeepCopyInto(out *PostgresExporter) {
	*out = *in
	if in.CustomQueries != nil {
		in, out := &in.CustomQueries, &out.CustomQueries
		*out = new(CustomQueries)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresExporter.
func (in *PostgresExporter) DeepCopy() *PostgresExporter {
	if in == nil {
		return nil
	}
	out := new(PostgresExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowaUI) DeepCopyInto(out *PowaUI) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowaUI.
func (in *PowaUI) DeepCopy() *PowaUI {
	if in == nil {
		return nil
	}
	out := new(PowaUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateRegistry) DeepCopyInto(out *PrivateRegistry) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateRegistry.
func (in *PrivateRegistry) DeepCopy() *PrivateRegistry {
	if in == nil {
		return nil
	}
	out := new(PrivateRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryExporter) DeepCopyInto(out *QueryExporter) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CustomQueries != nil {
		in, out := &in.CustomQueries, &out.CustomQueries
		*out = new(CustomQueries)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeQueries != nil {
		in, out := &in.ExcludeQueries, &out.ExcludeQueries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryExporter.
func (in *QueryExporter) DeepCopy() *QueryExporter {
	if in == nil {
		return nil
	}
	out := new(QueryExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationController) DeepCopyInto(out *ReplicationController) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationController.
func (in *ReplicationController) DeepCopy() *ReplicationController {
	if in == nil {
		return nil
	}
	out := new(ReplicationController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3) DeepCopyInto(out *S3) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3.
func (in *S3) DeepCopy() *S3 {
	if in == nil {
		return nil
	}
	out := new(S3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteManager) DeepCopyInto(out *SiteManager) {
	*out = *in
	if in.StandbyClusterHealthCheck != nil {
		in, out := &in.StandbyClusterHealthCheck, &out.StandbyClusterHealthCheck
		*out = new(StandbyClusterHealthCheck)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteManager.
func (in *SiteManager) DeepCopy() *SiteManager {
	if in == nil {
		return nil
	}
	out := new(SiteManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteManagerStatus) DeepCopyInto(out *SiteManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteManagerStatus.
func (in *SiteManagerStatus) DeepCopy() *SiteManagerStatus {
	if in == nil {
		return nil
	}
	out := new(SiteManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandbyClusterHealthCheck) DeepCopyInto(out *StandbyClusterHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandbyClusterHealthCheck.
func (in *StandbyClusterHealthCheck) DeepCopy() *StandbyClusterHealthCheck {
	if in == nil {
		return nil
	}
	out := new(StandbyClusterHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupplementaryPatroniServicessList) DeepCopyInto(out *SupplementaryPatroniServicessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PatroniServices, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupplementaryPatroniServicessList.
func (in *SupplementaryPatroniServicessList) DeepCopy() *SupplementaryPatroniServicessList {
	if in == nil {
		return nil
	}
	out := new(SupplementaryPatroniServicessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls) DeepCopyInto(out *Tls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls.
func (in *Tls) DeepCopy() *Tls {
	if in == nil {
		return nil
	}
	out := new(Tls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}
