{
 "title": "Query Exporter",
 "description": "Dashbord works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "postgres-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"query-exporter\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Project",
    "query": {
     "query": "label_values(up{job=\"query-exporter\", cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_datdba{namespace=\"$namespace\", cluster=~\"$cluster\"}, datname) "
    }
   },
   {
    "name": "interval2",
    "label": "Interval",
    "query": "1m,2m,3m,4m,5m,6m,7m,8m,9m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "grouping",
    "label": "Grouping",
    "query": "{{datname}} : 1, {{db_namespace}}|{{microservice}}|{{datname}} : on (namespace\\, datname) group_left(microservice\\, db_namespace) sum by (namespace\\,datname\\,microservice\\,db_namespace) (pg_dbaas_name), {{db_namespace}}|{{microservice}} : on (namespace\\, datname) group_left(microservice\\, db_namespace) sum by (namespace\\,datname\\,microservice\\,db_namespace) (pg_dbaas_name), {{microservice}} : on (namespace\\, datname) group_left(microservice\\, db_namespace) sum by (namespace\\,datname\\,microservice\\,db_namespace) (pg_dbaas_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Configuration and Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Instance current status.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_replication_is_replica{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Instance start time.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_postmaster_start_time_seconds{namespace=\"$namespace\", cluster=~\"$cluster\"})*1000"
    }
   ]
  },
  {
   "title": "Replica state",
   "type": "table",
   "description": "Synchronous state of standby server.",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "pg_stat_replicat_mode{namespace=\"$namespace\", cluster=~\"$cluster\"} OR on() vector(0)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Seq",
   "type": "stat",
   "description": "Total number of sequential scans initiated for tables in database.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_user_tables_seq_scan{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"} [$__rate_interval])>=0 )"
    }
   ]
  },
  {
   "title": "Ind",
   "type": "stat",
   "description": "Total number of index scans initiated for tables in database.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_user_tables_idx_scan{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])>=0)"
    }
   ]
  },
  {
   "title": "Archive Fails",
   "type": "stat",
   "description": "Time of the most recent failed archival operation.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_archive_last_failed_time{namespace=\"$namespace\", cluster=~\"$cluster\"})*1000",
     "legendFormat": "is_arc"
    }
   ]
  },
  {
   "title": "WAL Size",
   "type": "stat",
   "description": "Total WAL files size.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_wal_size{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "stat",
   "description": "Total WAL files rate.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_wal_size{namespace=\"$namespace\", cluster=~\"$cluster\"})/sum(pg_wal_duration{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of backends",
   "type": "stat",
   "description": "The number of backends connected to a certain database",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "description": "Number of deadlocks per logical database.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_deadlocks{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "description": "Number of transactions in this database that have been committed per second.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Number of queries per second.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_calls_per_sec{namespace=\"$namespace\" ,datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "stat",
   "description": "Replication lag behind master in seconds.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_repl_lag{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "TXID",
   "type": "gauge",
   "description": "The percentage of transaction ID space used out. Maximum TXID assumed as 2000000000.",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_txid_wraparound_percent_towards_wraparound{namespace=\"$namespace\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Oldest XID",
   "type": "table",
   "description": "Oldest XID for database instance.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "pg_txid_wraparound_oldest_current_xid{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "oldest_current_xid"
    }
   ]
  },
  {
   "title": "Database age",
   "type": "table",
   "description": "Largest database age.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "pg_largest_age_databases_age{namespace=\"$namespace\", cluster=~\"$cluster\"} * ${grouping:value}\r\nor on (namespace, datname)\r\npg_largest_age_databases_age{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "${grouping:text}"
    }
   ]
  },
  {
   "title": "WAL Archived",
   "type": "stat",
   "description": "Archived WALs per second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(pg_archive_current_archived_wals_per_second{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "WAL Files",
   "type": "stat",
   "description": "WAL files count.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_wal_count{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "DB Parameter Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pg_settings_setting{namespace=\"$namespace\", name=~\"port|server_version|tcp_keepalives_count|tcp_keepalives_interval\" }\n ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "pg_settings_checkpoint_setting{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "pg_settings_limits_setting{namespace=\"$namespace\", cluster=~\"$cluster\"}\n ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "pg_settings_wal_setting{namespace=\"$namespace\", name!=\"max_wal_size\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "pg_settings_wal_setting{namespace=\"$namespace\", name=~\"max_wal_size\", cluster=~\"$cluster\"}/1024",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_settings_misc_setting{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "pg_settings_optimizer_setting{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "pg_settings_memory_setting{namespace=\"$namespace\", name!=\"effective_cache_size\",name!=\"shared_buffers\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "pg_settings_memory_setting{namespace=\"$namespace\", name=~\"shared_buffers\", cluster=~\"$cluster\"}*8",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "pg_settings_memory_setting{namespace=\"$namespace\", name=~\"effective_cache_size\", cluster=~\"$cluster\"}*8",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Connection Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Connection by database",
   "type": "timeseries",
   "description": "Shows the number of connections per database.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$4",
     "expr": "connection_by_database_cnt{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"} * ${grouping:value}\r\nor on (namespace, datname)\r\nconnection_by_database_cnt{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "${grouping:text}",
     "query": "SELECT mean(\"value\") FROM /pg.common.connection_by_database.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connection by role",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "connection_by_role_cnt{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ usename }}"
    }
   ]
  },
  {
   "title": "Overall connection statistic",
   "type": "timeseries",
   "description": "Shows how many connections are in use right now. It shows max connections, used connections, reserved for regular, and superuser.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$4",
     "expr": "connection_count_stat_max_connections{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "stat max connections",
     "query": "SELECT mean(\"value\") FROM /pg.common.connection_count_stat.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "connection_count_stat_reserved_for_reg_users{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "reserved for reg_users"
    },
    {
     "expr": "connection_count_stat_reserved_for_superuser{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "reserved for superuser"
    },
    {
     "expr": "connection_count_stat_used{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Not idle connections by Database",
   "type": "timeseries",
   "description": "Shows the number of not idle connections per database.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$4",
     "expr": "count_not_idle_cnt{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"} * ${grouping:value}\r\nor on (namespace, datname)\r\ncount_not_idle_cnt{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "${grouping:text}",
     "query": "SELECT mean(\"value\") FROM /pg.common.count_not_idle.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Active Connections by Role",
   "type": "table",
   "description": "This table shows number of Active Connections in current moment by role. Also shows Connection Limits that is set during Role create. Also, shows not idle connection by role.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "last_over_time(connection_by_role_with_limit_role_cnt{namespace=\"$namespace\", cluster=~\"$cluster\"}[5m:])",
     "groupBy": [
      { "params": [ "queryid" ], "type": "tag" }
     ],
     "legendFormat": "Role",
     "measurement": "ma.pg.common.queries_stat",
     "query": "SELECT top(\"$column\", $limit) as \"$column\", \"short_query\", \"datname\", \"mean_time\", \"queryid\" FROM (SELECT LAST(\"queryid_val\"), * FROM \"ma.pg.common.queries_stat\" WHERE $timeFilter and (\"datname\" = '$datname' OR 'All' = '$datname' ) and \"namespace\" = '$namespace'  GROUP BY \"queryid\" ORDER BY DESC LIMIT 1) ORDER BY DESC",
     "select": [
      [
       { "params": [ "mean_time" ], "type": "field" },
       { "params": [ "30" ], "type": "top" }
      ],
      [
       { "params": [ "calls" ], "type": "field" }
      ],
      [
       { "params": [ "short_query" ], "type": "field" }
      ],
      [
       { "params": [ "datname" ], "type": "field" }
      ],
      [
       { "params": [ "total_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_act_cnt{datname=~\"$datname\", namespace=\"$namespace\", backend_type=\"client backend\",state=~\"idle|idle in transaction|idle in transaction (aborted)|active\", cluster=~\"$cluster\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(pg_stat_act_cnt{datname=~\"$datname\", namespace=\"$namespace\", backend_type!=\"client backend\",state=~\"idle|idle in transaction|idle in transaction (aborted)|active\", cluster=~\"$cluster\"})",
     "legendFormat": "background"
    }
   ]
  },
  {
   "title": "Idle process seconds",
   "type": "heatmap",
   "description": "Idle process seconds Heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_idle_process_seconds_bucket{namespace=\"$namespace\", cluster=~\"$cluster\", datname=~\"$datname\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_act_cnt{datname=~\"$datname\", namespace=\"$namespace\", backend_type!=\"client backend\",state=~\"idle|idle in transaction|idle in transaction (aborted)|active\", cluster=~\"$cluster\"}) by (backend_type)",
     "legendFormat": "{{ backend_type }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Fetched"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname, namespace) (irate(pg_stat_calls_per_sec{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])) * ${grouping:value}\r\nor on (namespace, datname)\r\nsum by (datname, namespace) (irate(pg_stat_calls_per_sec{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "${grouping:text}",
     "rawSql": "SELECT\n  current_timestamp AS \"time\",\n  event_type AS metric,\n  count(ps.pid) AS value\nFROM pg_wait_sampling_current pw, pg_stat_activity ps\nwhere ps.pid=pw.pid and state = 'active'\ngroup by current_timestamp,\nevent_type"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(pg_stat_tables_hot_upd{datname=~\"$datname\",namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Updated (HOT)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_conflicts{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "sum(pg_stat_database_deadlocks{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "scalar(pg_wal_size{namespace=\"$namespace\", cluster=~\"$cluster\"})*1024/(scalar(pg_wal_duration{namespace=\"$namespace\", cluster=~\"$cluster\"})*(irate(pg_stat_database_xact_commit{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])))  * ${grouping:value}\r\nor on (namespace, datname)\r\nscalar(pg_wal_size{namespace=\"$namespace\", cluster=~\"$cluster\"})*1024/(scalar(pg_wal_duration{namespace=\"$namespace\", cluster=~\"$cluster\"})*(irate(pg_stat_database_xact_commit{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "${grouping:text} (Tx WAL size)"
    }
   ]
  },
  {
   "title": "Dead tuples",
   "type": "table",
   "description": "Top 5 tables with higher amount of dead tuples",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum by (datname, relname, size) (pg_dead_tuple_percent{namespace=\"$namespace\", cluster=~\"$cluster\", datname=~\"$datname\"})))"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"} * ${grouping:value}\r\nor on (namespace, datname)\r\npg_database_size_bytes{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "${grouping:text} (Size)"
    },
    {
     "expr": "pg_database_real_size_bytes{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"} * ${grouping:value}\r\nor on (namespace, datname)\r\npg_database_real_size_bytes{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "${grouping:text} (Real Size)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "pg_stat_replicat_pending_write_data{namespace=\"$namespace\", cluster=~\"$cluster\"}Or vector(0)",
     "legendFormat": "{{ client }} <write>"
    },
    {
     "expr": "pg_stat_replicat_pending_flush_data{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ client }} <flush>"
    },
    {
     "expr": "pg_stat_replicat_pending_replay_data{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ client }} <replay>"
    }
   ]
  },
  {
   "title": "Buffers & Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "description": "Rate at which IO performed on buffers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Backends"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_alloc{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend_fsync{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Bbackend_fsync"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_checkpoint{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Checkpointer"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_clean{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_maxwritten_clean{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Maxwriten"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_temp_bytes{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TempFiles"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_buffercache_bufs{namespace=\"$namespace\", cluster=~\"$cluster\"} * 8192",
     "legendFormat": "Buffer"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_buffercache_freq_used_bufs{namespace=\"$namespace\", cluster=~\"$cluster\"} * 8192)",
     "legendFormat": "Hot"
    },
    {
     "expr": "sum(pg_buffercache_dirty_bufs{namespace=\"$namespace\", cluster=~\"$cluster\"}* 8192)",
     "legendFormat": "Dirty"
    },
    {
     "expr": "sum(pg_buffercache_bufs{namespace=\"$namespace\", cluster=~\"$cluster\"}* 8192)",
     "legendFormat": "InUse"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_checkpoints_req{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])) * 10",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_checkpoints_timed{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])) * 10",
     "legendFormat": "Timed"
    }
   ]
  },
  {
   "title": "Blocking Session Details",
   "type": "table",
   "description": "Sessions Blocking other session running simultaneously  in the database servers",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum by (blocked_user, blocked_pid, blocking_pid, blocking_user, mode) (pg_sess_rownum{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (event_type, event) (irate(pg_wait_type_count{namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])/1000 >= 0.05))  ",
     "legendFormat": "{{event_type}}: {{event}}"
    },
    {
     "expr": "(sum(irate(pg_wait_type_count{namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])/1000 < 0.05))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (event_type, event) (irate(pg_wait_type_count{cluster=~\"$cluster\"}[$__rate_interval])/100)",
     "legendFormat": "{{event_type}}: {{event}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "sum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_from_disk{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_from_disk{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_disk_hits_perc{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_disk_hits_perc{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_cache_hits_perc{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_cache_hits_perc{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_total_hits{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname,schemaname,table_name,namespace) (pg_statio_user_tables_total_hits{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock Tree Monitor",
   "type": "table",
   "description": "The table shows locks by table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "pg_lock_tree_info{namespace=\"$namespace\", datname=~\"$datname\"}",
     "groupBy": [
      { "params": [ "queryid" ], "type": "tag" }
     ],
     "measurement": "ma.pg.common.queries_stat",
     "query": "SELECT top(\"$column\", $limit) as \"$column\", \"short_query\", \"datname\", \"mean_time\", \"queryid\" FROM (SELECT LAST(\"queryid_val\"), * FROM \"ma.pg.common.queries_stat\" WHERE $timeFilter and (\"datname\" = '$datname' OR 'All' = '$datname' ) and \"namespace\" = '$namespace'  GROUP BY \"queryid\" ORDER BY DESC LIMIT 1) ORDER BY DESC",
     "select": [
      [
       { "params": [ "mean_time" ], "type": "field" },
       { "params": [ "30" ], "type": "top" }
      ],
      [
       { "params": [ "calls" ], "type": "field" }
      ],
      [
       { "params": [ "short_query" ], "type": "field" }
      ],
      [
       { "params": [ "datname" ], "type": "field" }
      ],
      [
       { "params": [ "total_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, irate(pg_stat_statements_shared_blks_read{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10, irate(pg_stat_statements_shared_blks_read{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "[${grouping:text}] {{query}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, irate(pg_stat_statements_shared_blks_dirtied{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10, irate(pg_stat_statements_shared_blks_dirtied{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "[${grouping:text}] {{query}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_replicat_write_lag{namespace=\"$namespace\", cluster=~\"$cluster\"} OR vector(0)",
     "legendFormat": "{{ client }} <write>"
    },
    {
     "expr": "pg_stat_replicat_flush_lag{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ client }} <flush>"
    },
    {
     "expr": "pg_stat_replicat_replay_lag{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ client }} <replay>"
    }
   ]
  },
  {
   "title": "Replication Slots Graph",
   "type": "timeseries",
   "description": "Describes information about replication slots",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_replicaiton_slots_monitoring_retained_wal{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Replication Slots ",
   "type": "table",
   "description": "Describes information about replication slots",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_replicaiton_slots_monitoring_retained_wal{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "groupBy": [
      { "params": [ "queryid" ], "type": "tag" }
     ],
     "measurement": "ma.pg.common.queries_stat",
     "query": "SELECT top(\"$column\", $limit) as \"$column\", \"short_query\", \"datname\", \"mean_time\", \"queryid\" FROM (SELECT LAST(\"queryid_val\"), * FROM \"ma.pg.common.queries_stat\" WHERE $timeFilter and (\"datname\" = '$datname' OR 'All' = '$datname' ) and \"namespace\" = '$namespace'  GROUP BY \"queryid\" ORDER BY DESC LIMIT 1) ORDER BY DESC",
     "select": [
      [
       { "params": [ "mean_time" ], "type": "field" },
       { "params": [ "30" ], "type": "top" }
      ],
      [
       { "params": [ "calls" ], "type": "field" }
      ],
      [
       { "params": [ "short_query" ], "type": "field" }
      ],
      [
       { "params": [ "datname" ], "type": "field" }
      ],
      [
       { "params": [ "total_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(10, (irate(pg_stat_long_running_totalTime{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])>1)*1000) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10, (irate(pg_stat_long_running_totalTime{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])>1)*1000)",
     "legendFormat": "[${grouping:text}] {{query}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,pg_stat_query_percentage_cpu{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10,pg_stat_query_percentage_cpu{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "[${grouping:text}] {{query}}"
    }
   ]
  },
  {
   "title": "Top temp blks written",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,pg_stat_query_temp_blks_written{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10,pg_stat_query_temp_blks_written{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "[${grouping:text}] {{query}}"
    }
   ]
  },
  {
   "title": "Shared Blocks",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "sum by (datname, query, rolname, queryid, namespace) (pg_stat_query_shared_blks_read{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname, query, rolname, queryid, namespace) (pg_stat_query_shared_blks_read{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, query, rolname, queryid) (pg_stat_query_shared_blks_written{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname, query, rolname, queryid) (pg_stat_query_shared_blks_written{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,(increase(pg_stat_statements_calls{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval:]))) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10,(increase(pg_stat_statements_calls{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval:])))",
     "legendFormat": "[${grouping:text}] {{query}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, (irate(pg_stat_statements_blk_read_time{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10, (irate(pg_stat_statements_blk_read_time{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "[${grouping:text}] {{query}} (read)"
    },
    {
     "expr": "topk(10, (irate(pg_stat_statements_blk_write_time{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval]))) * ${grouping:value}\r\nor on (namespace, datname)\r\ntopk(10, (irate(pg_stat_statements_blk_read_time{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "[${grouping:text}] {{query}} (write)"
    }
   ]
  },
  {
   "title": "Top Queries On CPU (%Time)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,avg by(query)(pg_pash_pct_time_spent{namespace=\"$namespace\",backend_type=\"client backend\",wait_event_type=\"CPU\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (query_text) (irate(pg_wait_query_count{namespace=\"$namespace\", query_text!=\"N/A\", cluster=~\"$cluster\"}[$__rate_interval])/100) or vector(0)",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "%time_For_SQLs (CPU and Waits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,avg by(query,wait_event_type)(pg_pash_pct_time_spent{datname=~\"$datname\",namespace=\"$namespace\", cluster=~\"$cluster\"})) ",
     "legendFormat": "{{wait_event_type}}: {{query}}"
    }
   ]
  },
  {
   "title": "Avg Active sessions Waiting By SQLs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,avg by (query,wait_event_type) (pg_pash_avg_active_sess{namespace=\"$namespace\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{wait_event_type}}:  {{query}}"
    }
   ]
  },
  {
   "title": "Vacuum And Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 246 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autovacuum sessions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 247 },
   "targets": [
    {
     "expr": "sum by (datname, pid, query, state, username, xact_runtime, namespace) (pg_stat_vacuum_rownum{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"}) * ${grouping:value} or on (namespace, datname)\r\nsum by (datname, pid, query, state, username, xact_runtime, namespace) (pg_stat_vacuum_rownum{datname=~\"$datname\", namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Progress For Vacuum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_progress_vacuum_phase{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pid}} {{relname}}: vacuum_phase"
    },
    {
     "expr": "pg_progress_vacuum_heap_blks_total{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pid}} {{relname}}: heap_blks_total"
    },
    {
     "expr": "pg_progress_vacuum_heap_blks_scanned{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pid}} {{relname}}:  heap_blks_scanned"
    },
    {
     "expr": "pg_progress_vacuum_heap_blks_vacuumed{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pid}} {{relname}}:  heap_blks_vacuumed"
    },
    {
     "expr": "pg_progress_vacuum_index_vacuum_count{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pid}} {{relname}}: index_vacuum_count "
    }
   ]
  },
  {
   "title": "Index scans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_progress_vacuum_phase{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{pid}} {{relname}} vacuum phase "
    },
    {
     "expr": "(pg_progress_vacuum_max_dead_tuples{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "{{pid}} {{relname}} max_dead_tuples_per _index_scan"
    },
    {
     "expr": "(pg_progress_vacuum_num_dead_tuples{namespace=\"$namespace\",datname=~\"$datname\", cluster=~\"$cluster\"})",
     "legendFormat": "{{pid}} {{relname}} dead_tuples_processed_in_current _index_scan"
    }
   ]
  },
  {
   "title": "Wait Event Stats_PASH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 265 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wait_event: Avg Active sessions Waiting",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 266 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(wait_event_type)(avg by (query,wait_event_type) (pg_pash_avg_active_sess{backend_type=\"client backend\" , namespace=\"$namespace\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{wait_event_type}}"
    }
   ]
  },
  {
   "title": "Wait_Event_Type for Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 266 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (query, wait_event_type) (avg by (query, wait_event_type)(pg_pash_avg_active_sess{namespace=\"$namespace\", cluster=~\"$cluster\"}) )",
     "legendFormat": "{{wait_event_type}} {{query}}",
     "rawSql": "SELECT\n  ash_time AS \"time\",\n  total_time\nFROM pg_stat_statements_history\nWHERE\n  $__timeFilter(ash_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wait_events per active sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 275 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(wait_event_type)(avg by (query,wait_event_type) (pg_pash_avg_active_sess{backend_type=\"client backend\", namespace=\"$namespace\", cluster=~\"$cluster\"}))/scalar(sum(pg_stat_act_cnt{datname=~\"$datname\", namespace=\"$namespace\", backend_type=\"client backend\",state=~\"idle in transaction|active\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{wait_event_type}}"
    }
   ]
  },
  {
   "title": "DBaaS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 284 },
   "collapsed": true,
   "panels": [
    {
     "title": "DBaaS Mappings",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 279 },
     "targets": [
      {
       "expr": "sum by (datname, db_namespace, microservice, tenant_id) (pg_dbaas_name{namespace=\"$namespace\", cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}