//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/Netcracker/pgskipper-operator-core/api/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulRegistration) DeepCopyInto(out *ConsulRegistration) {
	*out = *in
	if in.Meta != nil {
		in, out := &in.Meta, &out.Meta
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LeaderMeta != nil {
		in, out := &in.LeaderMeta, &out.LeaderMeta
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LeaderTags != nil {
		in, out := &in.LeaderTags, &out.LeaderTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulRegistration.
func (in *ConsulRegistration) DeepCopy() *ConsulRegistration {
	if in == nil {
		return nil
	}
	out := new(ConsulRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dcs) DeepCopyInto(out *Dcs) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dcs.
func (in *Dcs) DeepCopy() *Dcs {
	if in == nil {
		return nil
	}
	out := new(Dcs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *External) DeepCopyInto(out *External) {
	*out = *in
	if in.Pvc != nil {
		in, out := &in.Pvc, &out.Pvc
		*out = make([]PVC, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new External.
func (in *External) DeepCopy() *External {
	if in == nil {
		return nil
	}
	out := new(External)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTests) DeepCopyInto(out *IntegrationTests) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.TestList != nil {
		in, out := &in.TestList, &out.TestList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTests.
func (in *IntegrationTests) DeepCopy() *IntegrationTests {
	if in == nil {
		return nil
	}
	out := new(IntegrationTests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapConfig) DeepCopyInto(out *LdapConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapConfig.
func (in *LdapConfig) DeepCopy() *LdapConfig {
	if in == nil {
		return nil
	}
	out := new(LdapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVC) DeepCopyInto(out *PVC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVC.
func (in *PVC) DeepCopy() *PVC {
	if in == nil {
		return nil
	}
	out := new(PVC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patroni) DeepCopyInto(out *Patroni) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(apiv1.Storage)
		(*in).DeepCopyInto(*out)
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.PostgreSQLParams != nil {
		in, out := &in.PostgreSQLParams, &out.PostgreSQLParams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PatroniParams != nil {
		in, out := &in.PatroniParams, &out.PatroniParams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StandbyCluster != nil {
		in, out := &in.StandbyCluster, &out.StandbyCluster
		*out = new(StandbyCluster)
		**out = **in
	}
	in.Dcs.DeepCopyInto(&out.Dcs)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PgHba != nil {
		in, out := &in.PgHba, &out.PgHba
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Powa = in.Powa
	if in.VaultRegistration != nil {
		in, out := &in.VaultRegistration, &out.VaultRegistration
		*out = new(apiv1.VaultRegistration)
		**out = **in
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PgWalStorage != nil {
		in, out := &in.PgWalStorage, &out.PgWalStorage
		*out = new(apiv1.Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(External)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigMapAnnotations != nil {
		in, out := &in.ConfigMapAnnotations, &out.ConfigMapAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patroni.
func (in *Patroni) DeepCopy() *Patroni {
	if in == nil {
		return nil
	}
	out := new(Patroni)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniClusterSettings) DeepCopyInto(out *PatroniClusterSettings) {
	*out = *in
	if in.PatroniLabels != nil {
		in, out := &in.PatroniLabels, &out.PatroniLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PatroniCommonLabels != nil {
		in, out := &in.PatroniCommonLabels, &out.PatroniCommonLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PatroniMasterSelectors != nil {
		in, out := &in.PatroniMasterSelectors, &out.PatroniMasterSelectors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PatroniReplicasSelector != nil {
		in, out := &in.PatroniReplicasSelector, &out.PatroniReplicasSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniClusterSettings.
func (in *PatroniClusterSettings) DeepCopy() *PatroniClusterSettings {
	if in == nil {
		return nil
	}
	out := new(PatroniClusterSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniCore) DeepCopyInto(out *PatroniCore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(PatroniCoreSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(Upgrade)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniCore.
func (in *PatroniCore) DeepCopy() *PatroniCore {
	if in == nil {
		return nil
	}
	out := new(PatroniCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PatroniCore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniCoreList) DeepCopyInto(out *PatroniCoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PatroniCore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniCoreList.
func (in *PatroniCoreList) DeepCopy() *PatroniCoreList {
	if in == nil {
		return nil
	}
	out := new(PatroniCoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PatroniCoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniCoreSpec) DeepCopyInto(out *PatroniCoreSpec) {
	*out = *in
	if in.Patroni != nil {
		in, out := &in.Patroni, &out.Patroni
		*out = new(Patroni)
		(*in).DeepCopyInto(*out)
	}
	if in.IntegrationTests != nil {
		in, out := &in.IntegrationTests, &out.IntegrationTests
		*out = new(IntegrationTests)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsulRegistration != nil {
		in, out := &in.ConsulRegistration, &out.ConsulRegistration
		*out = new(ConsulRegistration)
		(*in).DeepCopyInto(*out)
	}
	if in.VaultRegistration != nil {
		in, out := &in.VaultRegistration, &out.VaultRegistration
		*out = new(apiv1.VaultRegistration)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(Policies)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudSql != nil {
		in, out := &in.CloudSql, &out.CloudSql
		*out = new(apiv1.CloudSql)
		**out = **in
	}
	if in.Tls != nil {
		in, out := &in.Tls, &out.Tls
		*out = new(Tls)
		**out = **in
	}
	if in.PgBackRest != nil {
		in, out := &in.PgBackRest, &out.PgBackRest
		*out = new(PgBackRest)
		(*in).DeepCopyInto(*out)
	}
	if in.Ldap != nil {
		in, out := &in.Ldap, &out.Ldap
		*out = new(LdapConfig)
		**out = **in
	}
	in.PrivateRegistry.DeepCopyInto(&out.PrivateRegistry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniCoreSpec.
func (in *PatroniCoreSpec) DeepCopy() *PatroniCoreSpec {
	if in == nil {
		return nil
	}
	out := new(PatroniCoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniCoreStatus) DeepCopyInto(out *PatroniCoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PatroniCoreStatusCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniCoreStatus.
func (in *PatroniCoreStatus) DeepCopy() *PatroniCoreStatus {
	if in == nil {
		return nil
	}
	out := new(PatroniCoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatroniCoreStatusCondition) DeepCopyInto(out *PatroniCoreStatusCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatroniCoreStatusCondition.
func (in *PatroniCoreStatusCondition) DeepCopy() *PatroniCoreStatusCondition {
	if in == nil {
		return nil
	}
	out := new(PatroniCoreStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgBackRest) DeepCopyInto(out *PgBackRest) {
	*out = *in
	out.S3 = in.S3
	if in.Rwx != nil {
		in, out := &in.Rwx, &out.Rwx
		*out = new(apiv1.Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigParams != nil {
		in, out := &in.ConfigParams, &out.ConfigParams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgBackRest.
func (in *PgBackRest) DeepCopy() *PgBackRest {
	if in == nil {
		return nil
	}
	out := new(PgBackRest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policies) DeepCopyInto(out *Policies) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policies.
func (in *Policies) DeepCopy() *Policies {
	if in == nil {
		return nil
	}
	out := new(Policies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Powa) DeepCopyInto(out *Powa) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Powa.
func (in *Powa) DeepCopy() *Powa {
	if in == nil {
		return nil
	}
	out := new(Powa)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateRegistry) DeepCopyInto(out *PrivateRegistry) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateRegistry.
func (in *PrivateRegistry) DeepCopy() *PrivateRegistry {
	if in == nil {
		return nil
	}
	out := new(PrivateRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3) DeepCopyInto(out *S3) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3.
func (in *S3) DeepCopy() *S3 {
	if in == nil {
		return nil
	}
	out := new(S3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandbyCluster) DeepCopyInto(out *StandbyCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandbyCluster.
func (in *StandbyCluster) DeepCopy() *StandbyCluster {
	if in == nil {
		return nil
	}
	out := new(StandbyCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandbyClusterHealthCheck) DeepCopyInto(out *StandbyClusterHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandbyClusterHealthCheck.
func (in *StandbyClusterHealthCheck) DeepCopy() *StandbyClusterHealthCheck {
	if in == nil {
		return nil
	}
	out := new(StandbyClusterHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls) DeepCopyInto(out *Tls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls.
func (in *Tls) DeepCopy() *Tls {
	if in == nil {
		return nil
	}
	out := new(Tls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upgrade) DeepCopyInto(out *Upgrade) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upgrade.
func (in *Upgrade) DeepCopy() *Upgrade {
	if in == nil {
		return nil
	}
	out := new(Upgrade)
	in.DeepCopyInto(out)
	return out
}
